const INCREMENT = 'INCREMENT'
const DECREMENT = 'DECREMENT'

const INCREMENT1 = 'INCREMENT1'
const DECREMENT1 = 'DECREMENT1'

const INCREMENT2 = 'INCREMENT2'
const DECREMENT2 = 'DECREMENT2'

export default {
  INCREMENT,
  INCREMENT1,
  INCREMENT2,
  DECREMENT,
  DECREMENT1,
  DECREMENT2
}
